### ISSUE TITLE
the problem of rename a parameter's name

### ISSUE THREAD

**Issue by jayce** [Kong/lua-multipart#24]
I am trying the delete and set_simple functions to rename a parameter's name, get a wrong answer. 
so I take time to checked some code, the problem is in https://github.com/Kong/lua-multipart/blob/master/src/multipart.lua#L274-L301.

And I create a sister PR #23

**Comment by bungle** [comment]
The #23 is merged, thank you @jayce. I'll prepare a release as soon as I get this repo green again on Travis.
