### ISSUE TITLE
Why don't parse the input using lua-resty-upload library instead?

### ISSUE THREAD

**Issue by zot24** [Kong/lua-multipart#3]
Just wondering why have you decided to do the parse manually instead of use this library https://github.com/openresty/lua-resty-upload?

This is just my first approach of using part of your logic + lua-resty-upload but I think it could be even cleaner https://gist.github.com/zot24/03e97fe48e74c4cb84a9

What do you think?

**Comment by bungle** [comment]
This is general purpose `Lua` library. `lua-resty-upload` requires OpenResty.

**Comment by zot24** [comment]
Appreciate your reply 5 year later 😄 I don't even remember last time I use Lua, will close this! thanks
