### ISSUE TITLE
File Format Change from csv to string while adding data in request body

### ISSUE THREAD

**Issue by vikas-nykaa** [Kong/lua-multipart#36]
I am adding one parameter in request body if POST request (Content-Type= "multipart-form/data") but after adding when i set edited body in kong request, file format changed from csv to string. Any suggestion?

Code:
local Multipart = require("multipart")
local multipart_data = Multipart(kong.request.get_raw_body(), kong.request.get_header("Content-Type"))
multipart_data["vendor"]="{ \"vendorId\" : \"vicky\", \"vendorName\" : \"vicky\" }"
kong.service.request.set_body(multipart_data)

Request Body:
<img width="811" alt="Screenshot 2021-11-14 at 4 16 59 PM" src="https://user-images.githubusercontent.com/86848951/141677757-c9c96ce3-4be5-4544-bbba-4ea29e6e5be6.png">

**Comment by Tieske** [comment]
That code does not look like valid Lua code to me.

**Comment by vikas-nykaa** [comment]
it is just selected code

**Comment by vikas-nykaa** [comment]
workinf fine after using multipart upgraded version
