### ISSUE TITLE
file decode failed

### ISSUE THREAD

**Issue by siadou** [Kong/lua-multipart#4]
I tried to decode the multipart encoded file and form data on my server 
for the text format file , the lines with only \r\n are lost
for the binary format file , the file is damaged

Is this parser can only be used for multipart/form-data encoded  form data  ? what about file ?

**Comment by Tieske** [comment]
first guess; Lua uses platform dependent line endings when writing text files. Now the lib doesn't do files, just parses and returns strings.

So are you writing the strings to a file, which ends up being corrupt? In that case, make sure you write the files in binary format.

**Comment by siadou** [comment]
Hi @Tieske 
When I decode the ASCII format file, this parser still doesn't work as it missed some characters
For example, here is the input file "index.file"

```
line1

line2

line3
```

The output is like this:

```
line1
line2
line3
```

the file is in DOS format , all the /r/n lines are disappeared !
i think this may be resulted from the following code in source code (function decode(),line 42)

```
...
 for line in body:gmatch("[^\r\n]+") do
    if ....
    .....
    else
      if is_header(line) then
         ..........
      else
        part_value = (part_value and part_value.."\r\n" or "")..line
      end
    end
...
```

when there is "\r\n\r\n\r\n" , it's handled as \r\n, as the expression "[^\r\n]+" (doesn't like function "explode" in php ) omits the redundance "\r\n"

**Comment by stevenzhaoun** [comment]
@siadou 
I found the same problem, all the \r\n lost.
Did you find the solution to this problem?

**Comment by Tieske** [comment]
apologies for the long delays! would it be possible to provide a testcase showing the faulty behaviour?

**Comment by jkorvin** [comment]
@Tieske , explicit example was above in message of @siadou .
Idea to fix this problem you can find in https://github.com/Mashape/lua-multipart/pull/6

**Comment by siadou** [comment]
@jkorvin thank you for your answer!

**Comment by jkorvin** [comment]
@siadou , is it means that problem was solved, since the issue is closed?
Yet I cannot see any commit, which solved the problem.
